version: '3'
services:
   app:
      container_name: Yarkesh
      restart: always
      build: .
      ports:
         - '8585:8585'
      links:
         - db
   db:
      container_name: postgres
      image: postgres
      ports:
         - '55987:5432'
      environment:
         POSTGRES_PASSWORD: 0123456789
         POSTGRES_USER: postgres
         POSTGRES_DB: Yarkesh
